#!/bin/sh
set -e

# generate shell script in target dir
rm -rf target/
mkdir -p target/

cp -r static/* target/
cp index.md target/

echo -e "#!/bin/sh\n#Autogenerated\nset -e\n" > target/index.sh
cat index.md | sed -n '/^```/,/^```/ p' | sed '/^```/ d' >> target/index.sh
echo '"$@"' >> target/index.sh 

# make sure devenv is installed first
(cd target/ &&
  sh index.sh install_dev_env)

# run all functions in shell script
(cd target/ &&
  FUNCTIONS=$(cat index.sh | grep -e "^function" | sed 's/function //' | sed 's/{//')
  for FUN in $FUNCTIONS; do
    sh -xe index.sh $FUN
  done

# generate html
  pandoc index.md -H head.htmlsnip -B before.htmlsnip -A after.htmlsnip --metadata="title=seandavis.sh" -s --toc -o index.html)

cp target/index.sh target/raw
